spring.application.name=demo
spring.main.web-application-type=servlet

ocr.veryfi.environment-url=https://api.veryfi.com/
ocr.veryfi.process-endpoint=/api/v8/partner/any-documents
ocr.veryfi.client-id=vrf21piRCe3iDVtEnRTrt9ld2f2RSx0lGY3PhBA
ocr.veryfi.client-secret=bMWaBd3lrBL31YDJrO2wjZHP0gItY19TZS3LgAJWKaDfFrujagv6rzPMBDPZ6fpVZzlawV8UCtSb7sSHH6R8C4NgKp7CgJeL6hPu2DJoOoHDeBM6aoM6RHLipDdelGPI
ocr.veryfi.username=ezedinahmed2021
ocr.veryfi.api-key=b61ca950c9782468fae01657aac815d5
ocr.veryfi.timeout-seconds=15
ocr.confidence-threshold=0.6
normalization.fuzzy.acceptance-threshold=0.10
normalization.fuzzy.ambiguity-delta=0.02
chapa.base-url=https://api.chapa.co/v1/transaction
chapa.secret-key=CHASECK_TEST-XXXXXXXXXXXX
